local modpath, S = ...

assert(loadfile(modpath .. "/mobkit/bh_ant.lua"))(modpath)
assert(loadfile(modpath .. "/mobkit/bh_aquatic.lua"))()
assert(loadfile(modpath .. "/mobkit/bh_arboreal.lua"))()
assert(loadfile(modpath .. "/mobkit/bh_attack.lua"))()
assert(loadfile(modpath .. "/mobkit/bh_bee.lua"))()
assert(loadfile(modpath .. "/mobkit/bh_breed.lua"))()
assert(loadfile(modpath .. "/mobkit/bh_fly.lua"))()
assert(loadfile(modpath .. "/mobkit/bh_follow.lua"))()
assert(loadfile(modpath .. "/mobkit/bh_herding.lua"))()
assert(loadfile(modpath .. "/mobkit/bh_hunt.lua"))()
assert(loadfile(modpath .. "/mobkit/bh_mount.lua"))()
assert(loadfile(modpath .. "/mobkit/bh_replace.lua"))()
assert(loadfile(modpath .. "/mobkit/bh_runaway.lua"))()
assert(loadfile(modpath .. "/mobkit/bh_teleport.lua"))()
assert(loadfile(modpath .. "/mobkit/bh_torch.lua"))()
assert(loadfile(modpath .. "/mobkit/br_ant.lua"))()
assert(loadfile(modpath .. "/mobkit/br_aquatic.lua"))()
assert(loadfile(modpath .. "/mobkit/br_bee.lua"))()
assert(loadfile(modpath .. "/mobkit/br_herbivore.lua"))()
assert(loadfile(modpath .. "/mobkit/br_monster.lua"))()
assert(loadfile(modpath .. "/mobkit/br_predator.lua"))()
assert(loadfile(modpath .. "/mobkit/br_semiaquatic.lua"))()
assert(loadfile(modpath .. "/mobkit/helper_functions.lua"))()
assert(loadfile(modpath .. "/mobkit/bh_head.lua"))()
