apiVersion: apps/v1
kind: Deployment
metadata:
  name: minland
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: minland
  template:
    metadata:
      labels:
        app: minland
    spec:
      restartPolicy: Always
      volumes:
        - name: minland-world-state
          persistentVolumeClaim:
            claimName: minland-world-state
      containers:
        - image: gcr.io/minland-gcp/minland:cbd74fc1e45c03e501afef43e51dd7a42db54109
          name: minland
          ports:
            - containerPort: 30000
              protocol: UDP
          volumeMounts:
            - mountPath: /config/minland/.minetest/worlds/world
              name: minland-world-state
