apiVersion: apps/v1
kind: Deployment
metadata:
  name: minland
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: minland
  template:
    metadata:
      labels:
        app: minland
    spec:
      containers:
        - image: gcr.io/minland-gcp/minland:latest
          name: minland
          ports:
            - containerPort: 30000
              protocol: UDP
