name: Deploy Minland container image
on:
  push:
    branches: [main]

jobs:
  build:
    environment: container-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '321.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud info
      - run: ./scripts/build.sh
      - run: gcloud builds submit --tag gcr.io/minland-gcp/minland:$GITHUB_SHA
      - run: echo "{commit_message}={`git log -1 --pretty=%B`}" >> $GITHUB_ENV
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - run: |
          git checkout --track origin/prod
          git rebase origin/main
      - run: sed -i 's/gcr\.io\/minland-gcp\/minland:.*$/gcr\.io\/minland-gcp\/minland:'"$GITHUB_SHA"'/' ./k8s/minland-deployment.yaml
      - env:
          commit_message: $commit_message
        run: |
          git commit -m "$commit_message \
          Update Minland container image tag" -a
      - name: Push changes to deploy branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: prod
          force: true
